os: osx
language: generic
before_install:
  - brew update
install:
  - brew install msitools
before_script:
  - echo $TRAVIS_TAG
script:
  # obtain version from git tag, if not a git tag, set to 1.19.1 for testing
  - if [[ ! -z "$TRAVIS_TAG" ]]; then version=$TRAVIS_TAG; else version=1.19.1; fi
  - VERSION=$version DEBUG=true source ./pandocDownload2zip.sh
after_success:
  - tree
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "$DEB"
    - "$debZip"
    - "$debWoExt.tar.gz"
    - "$PKG"
    - "$pkgZip"
    - "$MSI"
    - "$msiZip"
    - "$ZIP"
    - "$TAR"
  skip_cleanup: true
  on:
    tags: true
