language: generic
addons:
  apt:
    packages:
    - p7zip-full
install:
  - sudo apt-get install p7zip-full
script:
  # obtain version from git tag, if not a git tag, set to 1.19.1 for testing
  - if [[ ! -z "$TRAVIS_TAG" ]]; then version=$TRAVIS_TAG; else version=1.19.1; fi
  - VERSION=version source ./pandocDownload2zip.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "$debZip"
    - "$pkgZip"
    - "$msiZip"
  skip_cleanup: true
  on:
    tags: true
