language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - p7zip-full
install:
  - wget http://launchpadlibrarian.net/293727143/libc6_2.23-0ubuntu5_amd64.deb &&
    sudo dpkg -i libc6_2.23-0ubuntu5_amd64.deb
  - wget http://launchpadlibrarian.net/253246088/libgsf-1-common_1.14.36-1_all.deb &&
    sudo dpkg -i libgsf-1-common_1.14.36-1_all.deb
  - wget http://launchpadlibrarian.net/253246092/libgsf-1-114_1.14.36-1_amd64.deb &&
    sudo dpkg -i libgsf-1-114_1.14.36-1_amd64.deb
  - wget http://launchpadlibrarian.net/293727138/libc-bin_2.23-0ubuntu5_amd64.deb &&
    sudo dpkg -i libc-bin_2.23-0ubuntu5_amd64.deb
  - wget http://launchpadlibrarian.net/250277651/libgcab-1.0-0_0.7-1_amd64.deb &&
    sudo dpkg -i libgcab-1.0-0_0.7-1_amd64.deb
  - wget http://launchpadlibrarian.net/228973209/libmsi0_0.95-1_amd64.deb &&
    sudo dpkg -i libmsi0_0.95-1_amd64.deb
  - wget http://launchpadlibrarian.net/228973210/msitools_0.95-1_amd64.deb &&
    sudo dpkg -i msitools_0.95-1_amd64.deb
before_script:
  - echo $TRAVIS_TAG
script:
  # obtain version from git tag, if not a git tag, set to 1.19.1 for testing
  - if [[ ! -z "$TRAVIS_TAG" ]]; then version=$TRAVIS_TAG; else version=1.19.1; fi
  - VERSION=$version DEBUG=true source ./pandocDownload2zip.sh
after_success:
  - tree
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "$debZip"
    - "$pkgZip"
    - "$msiZip"
  skip_cleanup: true
  on:
    tags: true
