language: generic
addons:
  apt:
    packages:
    - p7zip-full
install:
  - wget http://launchpadlibrarian.net/228973210/msitools_0.95-1_amd64.deb &&
    sudo dpkg -i msitools_0.95-1_amd64.deb
before_script:
  - echo $TRAVIS_TAG
script:
  # obtain version from git tag, if not a git tag, set to 1.19.1 for testing
  - if [[ ! -z "$TRAVIS_TAG" ]]; then version=$TRAVIS_TAG; else version=1.19.1; fi
  - VERSION=$version DEBUG=true source ./pandocDownload2zip.sh
after_success:
  - tree
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "$debZip"
    - "$pkgZip"
    - "$msiZip"
  skip_cleanup: true
  on:
    tags: true
